/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LojaIndexRouteImport } from './routes/loja/index'
import { Route as CursosIndexRouteImport } from './routes/cursos/index'
import { Route as ContaIndexRouteImport } from './routes/conta/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LojaPedidosRouteImport } from './routes/loja/pedidos'
import { Route as LojaFavoritosRouteImport } from './routes/loja/favoritos'
import { Route as LojaCompararRouteImport } from './routes/loja/comparar'
import { Route as LojaCheckoutRouteImport } from './routes/loja/checkout'
import { Route as LojaCarrinhoRouteImport } from './routes/loja/carrinho'
import { Route as LojaBuscaRouteImport } from './routes/loja/busca'
import { Route as ContaWishlistRouteImport } from './routes/conta/wishlist'
import { Route as ContaPontosRouteImport } from './routes/conta/pontos'
import { Route as ContaPedidosRouteImport } from './routes/conta/pedidos'
import { Route as ContaEnderecosRouteImport } from './routes/conta/enderecos'
import { Route as ContaDownloadsRouteImport } from './routes/conta/downloads'
import { Route as ContaCursosRouteImport } from './routes/conta/cursos'
import { Route as ContaConfiguracoesRouteImport } from './routes/conta/configuracoes'
import { Route as ContaAssinaturasRouteImport } from './routes/conta/assinaturas'
import { Route as AdminRelatoriosRouteImport } from './routes/admin/relatorios'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminMarketingRouteImport } from './routes/admin/marketing'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminColecoesRouteImport } from './routes/admin/colecoes'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'
import { Route as LojaColecoesIndexRouteImport } from './routes/loja/colecoes/index'
import { Route as CursosAlunoIndexRouteImport } from './routes/cursos/aluno/index'
import { Route as CursosSlugIndexRouteImport } from './routes/cursos/$slug/index'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin/produtos/index'
import { Route as AdminFinanceiroIndexRouteImport } from './routes/admin/financeiro/index'
import { Route as AdminCursosIndexRouteImport } from './routes/admin/cursos/index'
import { Route as AdminCrmIndexRouteImport } from './routes/admin/crm/index'
import { Route as LojaProdutoSlugRouteImport } from './routes/loja/produto.$slug'
import { Route as LojaColecoesSlugRouteImport } from './routes/loja/colecoes/$slug'
import { Route as CursosCategoriaSlugRouteImport } from './routes/cursos/categoria.$slug'
import { Route as CursosAlunoProgressoRouteImport } from './routes/cursos/aluno/progresso'
import { Route as CursosAlunoDownloadsRouteImport } from './routes/cursos/aluno/downloads'
import { Route as CursosAlunoComentariosRouteImport } from './routes/cursos/aluno/comentarios'
import { Route as CursosAlunoCertificadosRouteImport } from './routes/cursos/aluno/certificados'
import { Route as CursosSlugPlayerRouteImport } from './routes/cursos/$slug/player'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin/produtos/novo'
import { Route as AdminProdutosSlugRouteImport } from './routes/admin/produtos/$slug'
import { Route as AdminFinanceiroRelatoriosRouteImport } from './routes/admin/financeiro/relatorios'
import { Route as AdminFinanceiroReceitasRouteImport } from './routes/admin/financeiro/receitas'
import { Route as AdminFinanceiroFluxoRouteImport } from './routes/admin/financeiro/fluxo'
import { Route as AdminFinanceiroDespesasRouteImport } from './routes/admin/financeiro/despesas'
import { Route as AdminCursosNovoRouteImport } from './routes/admin/cursos/novo'
import { Route as AdminCursosCategoriasRouteImport } from './routes/admin/cursos/categorias'
import { Route as AdminCursosSlugRouteImport } from './routes/admin/cursos/$slug'
import { Route as AdminCrmWhatsappRouteImport } from './routes/admin/crm/whatsapp'
import { Route as AdminCrmTagsRouteImport } from './routes/admin/crm/tags'
import { Route as AdminCrmSegmentacaoRouteImport } from './routes/admin/crm/segmentacao'
import { Route as AdminCrmFunilRouteImport } from './routes/admin/crm/funil'
import { Route as AdminCrmEmailsRouteImport } from './routes/admin/crm/emails'
import { Route as AdminCrmClientesRouteImport } from './routes/admin/crm/clientes'
import { Route as AdminCrmCampanhasRouteImport } from './routes/admin/crm/campanhas'
import { Route as AdminCrmAnotacoesRouteImport } from './routes/admin/crm/anotacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIndexRoute = LojaIndexRouteImport.update({
  id: '/loja/',
  path: '/loja/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaIndexRoute = ContaIndexRouteImport.update({
  id: '/conta/',
  path: '/conta/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaPedidosRoute = LojaPedidosRouteImport.update({
  id: '/loja/pedidos',
  path: '/loja/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaFavoritosRoute = LojaFavoritosRouteImport.update({
  id: '/loja/favoritos',
  path: '/loja/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaCompararRoute = LojaCompararRouteImport.update({
  id: '/loja/comparar',
  path: '/loja/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaCheckoutRoute = LojaCheckoutRouteImport.update({
  id: '/loja/checkout',
  path: '/loja/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaCarrinhoRoute = LojaCarrinhoRouteImport.update({
  id: '/loja/carrinho',
  path: '/loja/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaBuscaRoute = LojaBuscaRouteImport.update({
  id: '/loja/busca',
  path: '/loja/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaWishlistRoute = ContaWishlistRouteImport.update({
  id: '/conta/wishlist',
  path: '/conta/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaPontosRoute = ContaPontosRouteImport.update({
  id: '/conta/pontos',
  path: '/conta/pontos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaPedidosRoute = ContaPedidosRouteImport.update({
  id: '/conta/pedidos',
  path: '/conta/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaEnderecosRoute = ContaEnderecosRouteImport.update({
  id: '/conta/enderecos',
  path: '/conta/enderecos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaDownloadsRoute = ContaDownloadsRouteImport.update({
  id: '/conta/downloads',
  path: '/conta/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaCursosRoute = ContaCursosRouteImport.update({
  id: '/conta/cursos',
  path: '/conta/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaConfiguracoesRoute = ContaConfiguracoesRouteImport.update({
  id: '/conta/configuracoes',
  path: '/conta/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaAssinaturasRoute = ContaAssinaturasRouteImport.update({
  id: '/conta/assinaturas',
  path: '/conta/assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/admin/marketing',
  path: '/admin/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminColecoesRoute = AdminColecoesRouteImport.update({
  id: '/admin/colecoes',
  path: '/admin/colecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaColecoesIndexRoute = LojaColecoesIndexRouteImport.update({
  id: '/loja/colecoes/',
  path: '/loja/colecoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosAlunoIndexRoute = CursosAlunoIndexRouteImport.update({
  id: '/cursos/aluno/',
  path: '/cursos/aluno/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugIndexRoute = CursosSlugIndexRouteImport.update({
  id: '/cursos/$slug/',
  path: '/cursos/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/admin/produtos/',
  path: '/admin/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceiroIndexRoute = AdminFinanceiroIndexRouteImport.update({
  id: '/admin/financeiro/',
  path: '/admin/financeiro/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosIndexRoute = AdminCursosIndexRouteImport.update({
  id: '/admin/cursos/',
  path: '/admin/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmIndexRoute = AdminCrmIndexRouteImport.update({
  id: '/admin/crm/',
  path: '/admin/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaProdutoSlugRoute = LojaProdutoSlugRouteImport.update({
  id: '/loja/produto/$slug',
  path: '/loja/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaColecoesSlugRoute = LojaColecoesSlugRouteImport.update({
  id: '/loja/colecoes/$slug',
  path: '/loja/colecoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosCategoriaSlugRoute = CursosCategoriaSlugRouteImport.update({
  id: '/cursos/categoria/$slug',
  path: '/cursos/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosAlunoProgressoRoute = CursosAlunoProgressoRouteImport.update({
  id: '/cursos/aluno/progresso',
  path: '/cursos/aluno/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosAlunoDownloadsRoute = CursosAlunoDownloadsRouteImport.update({
  id: '/cursos/aluno/downloads',
  path: '/cursos/aluno/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosAlunoComentariosRoute = CursosAlunoComentariosRouteImport.update({
  id: '/cursos/aluno/comentarios',
  path: '/cursos/aluno/comentarios',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosAlunoCertificadosRoute = CursosAlunoCertificadosRouteImport.update({
  id: '/cursos/aluno/certificados',
  path: '/cursos/aluno/certificados',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugPlayerRoute = CursosSlugPlayerRouteImport.update({
  id: '/cursos/$slug/player',
  path: '/cursos/$slug/player',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/admin/produtos/novo',
  path: '/admin/produtos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosSlugRoute = AdminProdutosSlugRouteImport.update({
  id: '/admin/produtos/$slug',
  path: '/admin/produtos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceiroRelatoriosRoute =
  AdminFinanceiroRelatoriosRouteImport.update({
    id: '/admin/financeiro/relatorios',
    path: '/admin/financeiro/relatorios',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminFinanceiroReceitasRoute = AdminFinanceiroReceitasRouteImport.update({
  id: '/admin/financeiro/receitas',
  path: '/admin/financeiro/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceiroFluxoRoute = AdminFinanceiroFluxoRouteImport.update({
  id: '/admin/financeiro/fluxo',
  path: '/admin/financeiro/fluxo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceiroDespesasRoute = AdminFinanceiroDespesasRouteImport.update({
  id: '/admin/financeiro/despesas',
  path: '/admin/financeiro/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosNovoRoute = AdminCursosNovoRouteImport.update({
  id: '/admin/cursos/novo',
  path: '/admin/cursos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosCategoriasRoute = AdminCursosCategoriasRouteImport.update({
  id: '/admin/cursos/categorias',
  path: '/admin/cursos/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosSlugRoute = AdminCursosSlugRouteImport.update({
  id: '/admin/cursos/$slug',
  path: '/admin/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmWhatsappRoute = AdminCrmWhatsappRouteImport.update({
  id: '/admin/crm/whatsapp',
  path: '/admin/crm/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmTagsRoute = AdminCrmTagsRouteImport.update({
  id: '/admin/crm/tags',
  path: '/admin/crm/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmSegmentacaoRoute = AdminCrmSegmentacaoRouteImport.update({
  id: '/admin/crm/segmentacao',
  path: '/admin/crm/segmentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmFunilRoute = AdminCrmFunilRouteImport.update({
  id: '/admin/crm/funil',
  path: '/admin/crm/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmEmailsRoute = AdminCrmEmailsRouteImport.update({
  id: '/admin/crm/emails',
  path: '/admin/crm/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmClientesRoute = AdminCrmClientesRouteImport.update({
  id: '/admin/crm/clientes',
  path: '/admin/crm/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmCampanhasRoute = AdminCrmCampanhasRouteImport.update({
  id: '/admin/crm/campanhas',
  path: '/admin/crm/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmAnotacoesRoute = AdminCrmAnotacoesRouteImport.update({
  id: '/admin/crm/anotacoes',
  path: '/admin/crm/anotacoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/colecoes': typeof AdminColecoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/conta/assinaturas': typeof ContaAssinaturasRoute
  '/conta/configuracoes': typeof ContaConfiguracoesRoute
  '/conta/cursos': typeof ContaCursosRoute
  '/conta/downloads': typeof ContaDownloadsRoute
  '/conta/enderecos': typeof ContaEnderecosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/conta/pontos': typeof ContaPontosRoute
  '/conta/wishlist': typeof ContaWishlistRoute
  '/loja/busca': typeof LojaBuscaRoute
  '/loja/carrinho': typeof LojaCarrinhoRoute
  '/loja/checkout': typeof LojaCheckoutRoute
  '/loja/comparar': typeof LojaCompararRoute
  '/loja/favoritos': typeof LojaFavoritosRoute
  '/loja/pedidos': typeof LojaPedidosRoute
  '/admin/': typeof AdminIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/loja/': typeof LojaIndexRoute
  '/admin/crm/anotacoes': typeof AdminCrmAnotacoesRoute
  '/admin/crm/campanhas': typeof AdminCrmCampanhasRoute
  '/admin/crm/clientes': typeof AdminCrmClientesRoute
  '/admin/crm/emails': typeof AdminCrmEmailsRoute
  '/admin/crm/funil': typeof AdminCrmFunilRoute
  '/admin/crm/segmentacao': typeof AdminCrmSegmentacaoRoute
  '/admin/crm/tags': typeof AdminCrmTagsRoute
  '/admin/crm/whatsapp': typeof AdminCrmWhatsappRoute
  '/admin/cursos/$slug': typeof AdminCursosSlugRoute
  '/admin/cursos/categorias': typeof AdminCursosCategoriasRoute
  '/admin/cursos/novo': typeof AdminCursosNovoRoute
  '/admin/financeiro/despesas': typeof AdminFinanceiroDespesasRoute
  '/admin/financeiro/fluxo': typeof AdminFinanceiroFluxoRoute
  '/admin/financeiro/receitas': typeof AdminFinanceiroReceitasRoute
  '/admin/financeiro/relatorios': typeof AdminFinanceiroRelatoriosRoute
  '/admin/produtos/$slug': typeof AdminProdutosSlugRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/cursos/$slug/player': typeof CursosSlugPlayerRoute
  '/cursos/aluno/certificados': typeof CursosAlunoCertificadosRoute
  '/cursos/aluno/comentarios': typeof CursosAlunoComentariosRoute
  '/cursos/aluno/downloads': typeof CursosAlunoDownloadsRoute
  '/cursos/aluno/progresso': typeof CursosAlunoProgressoRoute
  '/cursos/categoria/$slug': typeof CursosCategoriaSlugRoute
  '/loja/colecoes/$slug': typeof LojaColecoesSlugRoute
  '/loja/produto/$slug': typeof LojaProdutoSlugRoute
  '/admin/crm/': typeof AdminCrmIndexRoute
  '/admin/cursos/': typeof AdminCursosIndexRoute
  '/admin/financeiro/': typeof AdminFinanceiroIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/cursos/$slug/': typeof CursosSlugIndexRoute
  '/cursos/aluno/': typeof CursosAlunoIndexRoute
  '/loja/colecoes/': typeof LojaColecoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/colecoes': typeof AdminColecoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/conta/assinaturas': typeof ContaAssinaturasRoute
  '/conta/configuracoes': typeof ContaConfiguracoesRoute
  '/conta/cursos': typeof ContaCursosRoute
  '/conta/downloads': typeof ContaDownloadsRoute
  '/conta/enderecos': typeof ContaEnderecosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/conta/pontos': typeof ContaPontosRoute
  '/conta/wishlist': typeof ContaWishlistRoute
  '/loja/busca': typeof LojaBuscaRoute
  '/loja/carrinho': typeof LojaCarrinhoRoute
  '/loja/checkout': typeof LojaCheckoutRoute
  '/loja/comparar': typeof LojaCompararRoute
  '/loja/favoritos': typeof LojaFavoritosRoute
  '/loja/pedidos': typeof LojaPedidosRoute
  '/admin': typeof AdminIndexRoute
  '/conta': typeof ContaIndexRoute
  '/cursos': typeof CursosIndexRoute
  '/loja': typeof LojaIndexRoute
  '/admin/crm/anotacoes': typeof AdminCrmAnotacoesRoute
  '/admin/crm/campanhas': typeof AdminCrmCampanhasRoute
  '/admin/crm/clientes': typeof AdminCrmClientesRoute
  '/admin/crm/emails': typeof AdminCrmEmailsRoute
  '/admin/crm/funil': typeof AdminCrmFunilRoute
  '/admin/crm/segmentacao': typeof AdminCrmSegmentacaoRoute
  '/admin/crm/tags': typeof AdminCrmTagsRoute
  '/admin/crm/whatsapp': typeof AdminCrmWhatsappRoute
  '/admin/cursos/$slug': typeof AdminCursosSlugRoute
  '/admin/cursos/categorias': typeof AdminCursosCategoriasRoute
  '/admin/cursos/novo': typeof AdminCursosNovoRoute
  '/admin/financeiro/despesas': typeof AdminFinanceiroDespesasRoute
  '/admin/financeiro/fluxo': typeof AdminFinanceiroFluxoRoute
  '/admin/financeiro/receitas': typeof AdminFinanceiroReceitasRoute
  '/admin/financeiro/relatorios': typeof AdminFinanceiroRelatoriosRoute
  '/admin/produtos/$slug': typeof AdminProdutosSlugRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/cursos/$slug/player': typeof CursosSlugPlayerRoute
  '/cursos/aluno/certificados': typeof CursosAlunoCertificadosRoute
  '/cursos/aluno/comentarios': typeof CursosAlunoComentariosRoute
  '/cursos/aluno/downloads': typeof CursosAlunoDownloadsRoute
  '/cursos/aluno/progresso': typeof CursosAlunoProgressoRoute
  '/cursos/categoria/$slug': typeof CursosCategoriaSlugRoute
  '/loja/colecoes/$slug': typeof LojaColecoesSlugRoute
  '/loja/produto/$slug': typeof LojaProdutoSlugRoute
  '/admin/crm': typeof AdminCrmIndexRoute
  '/admin/cursos': typeof AdminCursosIndexRoute
  '/admin/financeiro': typeof AdminFinanceiroIndexRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
  '/cursos/$slug': typeof CursosSlugIndexRoute
  '/cursos/aluno': typeof CursosAlunoIndexRoute
  '/loja/colecoes': typeof LojaColecoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/colecoes': typeof AdminColecoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/conta/assinaturas': typeof ContaAssinaturasRoute
  '/conta/configuracoes': typeof ContaConfiguracoesRoute
  '/conta/cursos': typeof ContaCursosRoute
  '/conta/downloads': typeof ContaDownloadsRoute
  '/conta/enderecos': typeof ContaEnderecosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/conta/pontos': typeof ContaPontosRoute
  '/conta/wishlist': typeof ContaWishlistRoute
  '/loja/busca': typeof LojaBuscaRoute
  '/loja/carrinho': typeof LojaCarrinhoRoute
  '/loja/checkout': typeof LojaCheckoutRoute
  '/loja/comparar': typeof LojaCompararRoute
  '/loja/favoritos': typeof LojaFavoritosRoute
  '/loja/pedidos': typeof LojaPedidosRoute
  '/admin/': typeof AdminIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/loja/': typeof LojaIndexRoute
  '/admin/crm/anotacoes': typeof AdminCrmAnotacoesRoute
  '/admin/crm/campanhas': typeof AdminCrmCampanhasRoute
  '/admin/crm/clientes': typeof AdminCrmClientesRoute
  '/admin/crm/emails': typeof AdminCrmEmailsRoute
  '/admin/crm/funil': typeof AdminCrmFunilRoute
  '/admin/crm/segmentacao': typeof AdminCrmSegmentacaoRoute
  '/admin/crm/tags': typeof AdminCrmTagsRoute
  '/admin/crm/whatsapp': typeof AdminCrmWhatsappRoute
  '/admin/cursos/$slug': typeof AdminCursosSlugRoute
  '/admin/cursos/categorias': typeof AdminCursosCategoriasRoute
  '/admin/cursos/novo': typeof AdminCursosNovoRoute
  '/admin/financeiro/despesas': typeof AdminFinanceiroDespesasRoute
  '/admin/financeiro/fluxo': typeof AdminFinanceiroFluxoRoute
  '/admin/financeiro/receitas': typeof AdminFinanceiroReceitasRoute
  '/admin/financeiro/relatorios': typeof AdminFinanceiroRelatoriosRoute
  '/admin/produtos/$slug': typeof AdminProdutosSlugRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/cursos/$slug/player': typeof CursosSlugPlayerRoute
  '/cursos/aluno/certificados': typeof CursosAlunoCertificadosRoute
  '/cursos/aluno/comentarios': typeof CursosAlunoComentariosRoute
  '/cursos/aluno/downloads': typeof CursosAlunoDownloadsRoute
  '/cursos/aluno/progresso': typeof CursosAlunoProgressoRoute
  '/cursos/categoria/$slug': typeof CursosCategoriaSlugRoute
  '/loja/colecoes/$slug': typeof LojaColecoesSlugRoute
  '/loja/produto/$slug': typeof LojaProdutoSlugRoute
  '/admin/crm/': typeof AdminCrmIndexRoute
  '/admin/cursos/': typeof AdminCursosIndexRoute
  '/admin/financeiro/': typeof AdminFinanceiroIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/cursos/$slug/': typeof CursosSlugIndexRoute
  '/cursos/aluno/': typeof CursosAlunoIndexRoute
  '/loja/colecoes/': typeof LojaColecoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/colecoes'
    | '/admin/configuracoes'
    | '/admin/marketing'
    | '/admin/pedidos'
    | '/admin/relatorios'
    | '/conta/assinaturas'
    | '/conta/configuracoes'
    | '/conta/cursos'
    | '/conta/downloads'
    | '/conta/enderecos'
    | '/conta/pedidos'
    | '/conta/pontos'
    | '/conta/wishlist'
    | '/loja/busca'
    | '/loja/carrinho'
    | '/loja/checkout'
    | '/loja/comparar'
    | '/loja/favoritos'
    | '/loja/pedidos'
    | '/admin/'
    | '/conta/'
    | '/cursos/'
    | '/loja/'
    | '/admin/crm/anotacoes'
    | '/admin/crm/campanhas'
    | '/admin/crm/clientes'
    | '/admin/crm/emails'
    | '/admin/crm/funil'
    | '/admin/crm/segmentacao'
    | '/admin/crm/tags'
    | '/admin/crm/whatsapp'
    | '/admin/cursos/$slug'
    | '/admin/cursos/categorias'
    | '/admin/cursos/novo'
    | '/admin/financeiro/despesas'
    | '/admin/financeiro/fluxo'
    | '/admin/financeiro/receitas'
    | '/admin/financeiro/relatorios'
    | '/admin/produtos/$slug'
    | '/admin/produtos/novo'
    | '/cursos/$slug/player'
    | '/cursos/aluno/certificados'
    | '/cursos/aluno/comentarios'
    | '/cursos/aluno/downloads'
    | '/cursos/aluno/progresso'
    | '/cursos/categoria/$slug'
    | '/loja/colecoes/$slug'
    | '/loja/produto/$slug'
    | '/admin/crm/'
    | '/admin/cursos/'
    | '/admin/financeiro/'
    | '/admin/produtos/'
    | '/cursos/$slug/'
    | '/cursos/aluno/'
    | '/loja/colecoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/colecoes'
    | '/admin/configuracoes'
    | '/admin/marketing'
    | '/admin/pedidos'
    | '/admin/relatorios'
    | '/conta/assinaturas'
    | '/conta/configuracoes'
    | '/conta/cursos'
    | '/conta/downloads'
    | '/conta/enderecos'
    | '/conta/pedidos'
    | '/conta/pontos'
    | '/conta/wishlist'
    | '/loja/busca'
    | '/loja/carrinho'
    | '/loja/checkout'
    | '/loja/comparar'
    | '/loja/favoritos'
    | '/loja/pedidos'
    | '/admin'
    | '/conta'
    | '/cursos'
    | '/loja'
    | '/admin/crm/anotacoes'
    | '/admin/crm/campanhas'
    | '/admin/crm/clientes'
    | '/admin/crm/emails'
    | '/admin/crm/funil'
    | '/admin/crm/segmentacao'
    | '/admin/crm/tags'
    | '/admin/crm/whatsapp'
    | '/admin/cursos/$slug'
    | '/admin/cursos/categorias'
    | '/admin/cursos/novo'
    | '/admin/financeiro/despesas'
    | '/admin/financeiro/fluxo'
    | '/admin/financeiro/receitas'
    | '/admin/financeiro/relatorios'
    | '/admin/produtos/$slug'
    | '/admin/produtos/novo'
    | '/cursos/$slug/player'
    | '/cursos/aluno/certificados'
    | '/cursos/aluno/comentarios'
    | '/cursos/aluno/downloads'
    | '/cursos/aluno/progresso'
    | '/cursos/categoria/$slug'
    | '/loja/colecoes/$slug'
    | '/loja/produto/$slug'
    | '/admin/crm'
    | '/admin/cursos'
    | '/admin/financeiro'
    | '/admin/produtos'
    | '/cursos/$slug'
    | '/cursos/aluno'
    | '/loja/colecoes'
  id:
    | '__root__'
    | '/'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/colecoes'
    | '/admin/configuracoes'
    | '/admin/marketing'
    | '/admin/pedidos'
    | '/admin/relatorios'
    | '/conta/assinaturas'
    | '/conta/configuracoes'
    | '/conta/cursos'
    | '/conta/downloads'
    | '/conta/enderecos'
    | '/conta/pedidos'
    | '/conta/pontos'
    | '/conta/wishlist'
    | '/loja/busca'
    | '/loja/carrinho'
    | '/loja/checkout'
    | '/loja/comparar'
    | '/loja/favoritos'
    | '/loja/pedidos'
    | '/admin/'
    | '/conta/'
    | '/cursos/'
    | '/loja/'
    | '/admin/crm/anotacoes'
    | '/admin/crm/campanhas'
    | '/admin/crm/clientes'
    | '/admin/crm/emails'
    | '/admin/crm/funil'
    | '/admin/crm/segmentacao'
    | '/admin/crm/tags'
    | '/admin/crm/whatsapp'
    | '/admin/cursos/$slug'
    | '/admin/cursos/categorias'
    | '/admin/cursos/novo'
    | '/admin/financeiro/despesas'
    | '/admin/financeiro/fluxo'
    | '/admin/financeiro/receitas'
    | '/admin/financeiro/relatorios'
    | '/admin/produtos/$slug'
    | '/admin/produtos/novo'
    | '/cursos/$slug/player'
    | '/cursos/aluno/certificados'
    | '/cursos/aluno/comentarios'
    | '/cursos/aluno/downloads'
    | '/cursos/aluno/progresso'
    | '/cursos/categoria/$slug'
    | '/loja/colecoes/$slug'
    | '/loja/produto/$slug'
    | '/admin/crm/'
    | '/admin/cursos/'
    | '/admin/financeiro/'
    | '/admin/produtos/'
    | '/cursos/$slug/'
    | '/cursos/aluno/'
    | '/loja/colecoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminColecoesRoute: typeof AdminColecoesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  ContaAssinaturasRoute: typeof ContaAssinaturasRoute
  ContaConfiguracoesRoute: typeof ContaConfiguracoesRoute
  ContaCursosRoute: typeof ContaCursosRoute
  ContaDownloadsRoute: typeof ContaDownloadsRoute
  ContaEnderecosRoute: typeof ContaEnderecosRoute
  ContaPedidosRoute: typeof ContaPedidosRoute
  ContaPontosRoute: typeof ContaPontosRoute
  ContaWishlistRoute: typeof ContaWishlistRoute
  LojaBuscaRoute: typeof LojaBuscaRoute
  LojaCarrinhoRoute: typeof LojaCarrinhoRoute
  LojaCheckoutRoute: typeof LojaCheckoutRoute
  LojaCompararRoute: typeof LojaCompararRoute
  LojaFavoritosRoute: typeof LojaFavoritosRoute
  LojaPedidosRoute: typeof LojaPedidosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ContaIndexRoute: typeof ContaIndexRoute
  CursosIndexRoute: typeof CursosIndexRoute
  LojaIndexRoute: typeof LojaIndexRoute
  AdminCrmAnotacoesRoute: typeof AdminCrmAnotacoesRoute
  AdminCrmCampanhasRoute: typeof AdminCrmCampanhasRoute
  AdminCrmClientesRoute: typeof AdminCrmClientesRoute
  AdminCrmEmailsRoute: typeof AdminCrmEmailsRoute
  AdminCrmFunilRoute: typeof AdminCrmFunilRoute
  AdminCrmSegmentacaoRoute: typeof AdminCrmSegmentacaoRoute
  AdminCrmTagsRoute: typeof AdminCrmTagsRoute
  AdminCrmWhatsappRoute: typeof AdminCrmWhatsappRoute
  AdminCursosSlugRoute: typeof AdminCursosSlugRoute
  AdminCursosCategoriasRoute: typeof AdminCursosCategoriasRoute
  AdminCursosNovoRoute: typeof AdminCursosNovoRoute
  AdminFinanceiroDespesasRoute: typeof AdminFinanceiroDespesasRoute
  AdminFinanceiroFluxoRoute: typeof AdminFinanceiroFluxoRoute
  AdminFinanceiroReceitasRoute: typeof AdminFinanceiroReceitasRoute
  AdminFinanceiroRelatoriosRoute: typeof AdminFinanceiroRelatoriosRoute
  AdminProdutosSlugRoute: typeof AdminProdutosSlugRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  CursosSlugPlayerRoute: typeof CursosSlugPlayerRoute
  CursosAlunoCertificadosRoute: typeof CursosAlunoCertificadosRoute
  CursosAlunoComentariosRoute: typeof CursosAlunoComentariosRoute
  CursosAlunoDownloadsRoute: typeof CursosAlunoDownloadsRoute
  CursosAlunoProgressoRoute: typeof CursosAlunoProgressoRoute
  CursosCategoriaSlugRoute: typeof CursosCategoriaSlugRoute
  LojaColecoesSlugRoute: typeof LojaColecoesSlugRoute
  LojaProdutoSlugRoute: typeof LojaProdutoSlugRoute
  AdminCrmIndexRoute: typeof AdminCrmIndexRoute
  AdminCursosIndexRoute: typeof AdminCursosIndexRoute
  AdminFinanceiroIndexRoute: typeof AdminFinanceiroIndexRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
  CursosSlugIndexRoute: typeof CursosSlugIndexRoute
  CursosAlunoIndexRoute: typeof CursosAlunoIndexRoute
  LojaColecoesIndexRoute: typeof LojaColecoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/': {
      id: '/loja/'
      path: '/loja'
      fullPath: '/loja/'
      preLoaderRoute: typeof LojaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/': {
      id: '/conta/'
      path: '/conta'
      fullPath: '/conta/'
      preLoaderRoute: typeof ContaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/pedidos': {
      id: '/loja/pedidos'
      path: '/loja/pedidos'
      fullPath: '/loja/pedidos'
      preLoaderRoute: typeof LojaPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/favoritos': {
      id: '/loja/favoritos'
      path: '/loja/favoritos'
      fullPath: '/loja/favoritos'
      preLoaderRoute: typeof LojaFavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/comparar': {
      id: '/loja/comparar'
      path: '/loja/comparar'
      fullPath: '/loja/comparar'
      preLoaderRoute: typeof LojaCompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/checkout': {
      id: '/loja/checkout'
      path: '/loja/checkout'
      fullPath: '/loja/checkout'
      preLoaderRoute: typeof LojaCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/carrinho': {
      id: '/loja/carrinho'
      path: '/loja/carrinho'
      fullPath: '/loja/carrinho'
      preLoaderRoute: typeof LojaCarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/busca': {
      id: '/loja/busca'
      path: '/loja/busca'
      fullPath: '/loja/busca'
      preLoaderRoute: typeof LojaBuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/wishlist': {
      id: '/conta/wishlist'
      path: '/conta/wishlist'
      fullPath: '/conta/wishlist'
      preLoaderRoute: typeof ContaWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/pontos': {
      id: '/conta/pontos'
      path: '/conta/pontos'
      fullPath: '/conta/pontos'
      preLoaderRoute: typeof ContaPontosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/pedidos': {
      id: '/conta/pedidos'
      path: '/conta/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof ContaPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/enderecos': {
      id: '/conta/enderecos'
      path: '/conta/enderecos'
      fullPath: '/conta/enderecos'
      preLoaderRoute: typeof ContaEnderecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/downloads': {
      id: '/conta/downloads'
      path: '/conta/downloads'
      fullPath: '/conta/downloads'
      preLoaderRoute: typeof ContaDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/cursos': {
      id: '/conta/cursos'
      path: '/conta/cursos'
      fullPath: '/conta/cursos'
      preLoaderRoute: typeof ContaCursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/configuracoes': {
      id: '/conta/configuracoes'
      path: '/conta/configuracoes'
      fullPath: '/conta/configuracoes'
      preLoaderRoute: typeof ContaConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/assinaturas': {
      id: '/conta/assinaturas'
      path: '/conta/assinaturas'
      fullPath: '/conta/assinaturas'
      preLoaderRoute: typeof ContaAssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/admin/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/colecoes': {
      id: '/admin/colecoes'
      path: '/admin/colecoes'
      fullPath: '/admin/colecoes'
      preLoaderRoute: typeof AdminColecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/colecoes/': {
      id: '/loja/colecoes/'
      path: '/loja/colecoes'
      fullPath: '/loja/colecoes/'
      preLoaderRoute: typeof LojaColecoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/aluno/': {
      id: '/cursos/aluno/'
      path: '/cursos/aluno'
      fullPath: '/cursos/aluno/'
      preLoaderRoute: typeof CursosAlunoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug/': {
      id: '/cursos/$slug/'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug/'
      preLoaderRoute: typeof CursosSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/admin/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro/': {
      id: '/admin/financeiro/'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro/'
      preLoaderRoute: typeof AdminFinanceiroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/': {
      id: '/admin/cursos/'
      path: '/admin/cursos'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AdminCursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/': {
      id: '/admin/crm/'
      path: '/admin/crm'
      fullPath: '/admin/crm/'
      preLoaderRoute: typeof AdminCrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/produto/$slug': {
      id: '/loja/produto/$slug'
      path: '/loja/produto/$slug'
      fullPath: '/loja/produto/$slug'
      preLoaderRoute: typeof LojaProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/colecoes/$slug': {
      id: '/loja/colecoes/$slug'
      path: '/loja/colecoes/$slug'
      fullPath: '/loja/colecoes/$slug'
      preLoaderRoute: typeof LojaColecoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/categoria/$slug': {
      id: '/cursos/categoria/$slug'
      path: '/cursos/categoria/$slug'
      fullPath: '/cursos/categoria/$slug'
      preLoaderRoute: typeof CursosCategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/aluno/progresso': {
      id: '/cursos/aluno/progresso'
      path: '/cursos/aluno/progresso'
      fullPath: '/cursos/aluno/progresso'
      preLoaderRoute: typeof CursosAlunoProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/aluno/downloads': {
      id: '/cursos/aluno/downloads'
      path: '/cursos/aluno/downloads'
      fullPath: '/cursos/aluno/downloads'
      preLoaderRoute: typeof CursosAlunoDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/aluno/comentarios': {
      id: '/cursos/aluno/comentarios'
      path: '/cursos/aluno/comentarios'
      fullPath: '/cursos/aluno/comentarios'
      preLoaderRoute: typeof CursosAlunoComentariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/aluno/certificados': {
      id: '/cursos/aluno/certificados'
      path: '/cursos/aluno/certificados'
      fullPath: '/cursos/aluno/certificados'
      preLoaderRoute: typeof CursosAlunoCertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug/player': {
      id: '/cursos/$slug/player'
      path: '/cursos/$slug/player'
      fullPath: '/cursos/$slug/player'
      preLoaderRoute: typeof CursosSlugPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/admin/produtos/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/$slug': {
      id: '/admin/produtos/$slug'
      path: '/admin/produtos/$slug'
      fullPath: '/admin/produtos/$slug'
      preLoaderRoute: typeof AdminProdutosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro/relatorios': {
      id: '/admin/financeiro/relatorios'
      path: '/admin/financeiro/relatorios'
      fullPath: '/admin/financeiro/relatorios'
      preLoaderRoute: typeof AdminFinanceiroRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro/receitas': {
      id: '/admin/financeiro/receitas'
      path: '/admin/financeiro/receitas'
      fullPath: '/admin/financeiro/receitas'
      preLoaderRoute: typeof AdminFinanceiroReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro/fluxo': {
      id: '/admin/financeiro/fluxo'
      path: '/admin/financeiro/fluxo'
      fullPath: '/admin/financeiro/fluxo'
      preLoaderRoute: typeof AdminFinanceiroFluxoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro/despesas': {
      id: '/admin/financeiro/despesas'
      path: '/admin/financeiro/despesas'
      fullPath: '/admin/financeiro/despesas'
      preLoaderRoute: typeof AdminFinanceiroDespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/novo': {
      id: '/admin/cursos/novo'
      path: '/admin/cursos/novo'
      fullPath: '/admin/cursos/novo'
      preLoaderRoute: typeof AdminCursosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/categorias': {
      id: '/admin/cursos/categorias'
      path: '/admin/cursos/categorias'
      fullPath: '/admin/cursos/categorias'
      preLoaderRoute: typeof AdminCursosCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/$slug': {
      id: '/admin/cursos/$slug'
      path: '/admin/cursos/$slug'
      fullPath: '/admin/cursos/$slug'
      preLoaderRoute: typeof AdminCursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/whatsapp': {
      id: '/admin/crm/whatsapp'
      path: '/admin/crm/whatsapp'
      fullPath: '/admin/crm/whatsapp'
      preLoaderRoute: typeof AdminCrmWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/tags': {
      id: '/admin/crm/tags'
      path: '/admin/crm/tags'
      fullPath: '/admin/crm/tags'
      preLoaderRoute: typeof AdminCrmTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/segmentacao': {
      id: '/admin/crm/segmentacao'
      path: '/admin/crm/segmentacao'
      fullPath: '/admin/crm/segmentacao'
      preLoaderRoute: typeof AdminCrmSegmentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/funil': {
      id: '/admin/crm/funil'
      path: '/admin/crm/funil'
      fullPath: '/admin/crm/funil'
      preLoaderRoute: typeof AdminCrmFunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/emails': {
      id: '/admin/crm/emails'
      path: '/admin/crm/emails'
      fullPath: '/admin/crm/emails'
      preLoaderRoute: typeof AdminCrmEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/clientes': {
      id: '/admin/crm/clientes'
      path: '/admin/crm/clientes'
      fullPath: '/admin/crm/clientes'
      preLoaderRoute: typeof AdminCrmClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/campanhas': {
      id: '/admin/crm/campanhas'
      path: '/admin/crm/campanhas'
      fullPath: '/admin/crm/campanhas'
      preLoaderRoute: typeof AdminCrmCampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/anotacoes': {
      id: '/admin/crm/anotacoes'
      path: '/admin/crm/anotacoes'
      fullPath: '/admin/crm/anotacoes'
      preLoaderRoute: typeof AdminCrmAnotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminColecoesRoute: AdminColecoesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  ContaAssinaturasRoute: ContaAssinaturasRoute,
  ContaConfiguracoesRoute: ContaConfiguracoesRoute,
  ContaCursosRoute: ContaCursosRoute,
  ContaDownloadsRoute: ContaDownloadsRoute,
  ContaEnderecosRoute: ContaEnderecosRoute,
  ContaPedidosRoute: ContaPedidosRoute,
  ContaPontosRoute: ContaPontosRoute,
  ContaWishlistRoute: ContaWishlistRoute,
  LojaBuscaRoute: LojaBuscaRoute,
  LojaCarrinhoRoute: LojaCarrinhoRoute,
  LojaCheckoutRoute: LojaCheckoutRoute,
  LojaCompararRoute: LojaCompararRoute,
  LojaFavoritosRoute: LojaFavoritosRoute,
  LojaPedidosRoute: LojaPedidosRoute,
  AdminIndexRoute: AdminIndexRoute,
  ContaIndexRoute: ContaIndexRoute,
  CursosIndexRoute: CursosIndexRoute,
  LojaIndexRoute: LojaIndexRoute,
  AdminCrmAnotacoesRoute: AdminCrmAnotacoesRoute,
  AdminCrmCampanhasRoute: AdminCrmCampanhasRoute,
  AdminCrmClientesRoute: AdminCrmClientesRoute,
  AdminCrmEmailsRoute: AdminCrmEmailsRoute,
  AdminCrmFunilRoute: AdminCrmFunilRoute,
  AdminCrmSegmentacaoRoute: AdminCrmSegmentacaoRoute,
  AdminCrmTagsRoute: AdminCrmTagsRoute,
  AdminCrmWhatsappRoute: AdminCrmWhatsappRoute,
  AdminCursosSlugRoute: AdminCursosSlugRoute,
  AdminCursosCategoriasRoute: AdminCursosCategoriasRoute,
  AdminCursosNovoRoute: AdminCursosNovoRoute,
  AdminFinanceiroDespesasRoute: AdminFinanceiroDespesasRoute,
  AdminFinanceiroFluxoRoute: AdminFinanceiroFluxoRoute,
  AdminFinanceiroReceitasRoute: AdminFinanceiroReceitasRoute,
  AdminFinanceiroRelatoriosRoute: AdminFinanceiroRelatoriosRoute,
  AdminProdutosSlugRoute: AdminProdutosSlugRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  CursosSlugPlayerRoute: CursosSlugPlayerRoute,
  CursosAlunoCertificadosRoute: CursosAlunoCertificadosRoute,
  CursosAlunoComentariosRoute: CursosAlunoComentariosRoute,
  CursosAlunoDownloadsRoute: CursosAlunoDownloadsRoute,
  CursosAlunoProgressoRoute: CursosAlunoProgressoRoute,
  CursosCategoriaSlugRoute: CursosCategoriaSlugRoute,
  LojaColecoesSlugRoute: LojaColecoesSlugRoute,
  LojaProdutoSlugRoute: LojaProdutoSlugRoute,
  AdminCrmIndexRoute: AdminCrmIndexRoute,
  AdminCursosIndexRoute: AdminCursosIndexRoute,
  AdminFinanceiroIndexRoute: AdminFinanceiroIndexRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
  CursosSlugIndexRoute: CursosSlugIndexRoute,
  CursosAlunoIndexRoute: CursosAlunoIndexRoute,
  LojaColecoesIndexRoute: LojaColecoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
